//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageMaster
    {
        public int PageID { get; set; }
        public int MenuID { get; set; }
        public string PageCaption { get; set; }
        public string PageURL { get; set; }
        public bool bitMenuDefaultPage { get; set; }
        public bool IsMaintenance { get; set; }
        public string MaintenanceMessage { get; set; }
        public int CommandID { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateIP { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateIP { get; set; }
    }
}
